export type FactConfidence = "VERIFIED" | "USER_RECALLED" | "PENDING_DETAIL";
export type RelationshipKind = "employment" | "independent" | "founder";

export type CareerProject = {
  id: string; name: string; shortLabel: string; companyId: string; period: string;
  aliases?: readonly string[];
  domain: string; summary: string; technologies: readonly string[];
  engineeringAreas: readonly string[]; confidence: FactConfidence; public: boolean;
  href?: string;
  detail?: { problem: string; architecture: string; engineering: string; lessons: string; interviewTopics: readonly string[]; future: string };
};

export type CareerCompany = {
  id: string; name: string; role: string; period: string; location?: string;
  relationship: RelationshipKind; public: boolean; projectIds: readonly string[];
};

export const companies: readonly CareerCompany[] = [
  { id: "independent", name: "Independent Product Engineering & AI", role: "Senior Full Stack / Product Engineer", period: "March 2026 — Present", relationship: "independent", public: true, projectIds: ["rentora", "edvora", "loom", "streamora"] },
  { id: "barclays", name: "Barclays", role: "Enterprise Engineering", period: "October 2021 — March 2026", relationship: "employment", public: true, projectIds: ["mastercard-vocalink", "barclays-identification-verification", "amazon-connect-voice"] },
  { id: "sysnik", name: "Sysnik IT Solutions Pvt. Ltd.", role: "Senior Software Engineer", period: "December 2018 — October 2021", location: "Pune, India", relationship: "employment", public: true, projectIds: ["master-table-management", "syscore-cbs", "reporting-framework", "ui-builder"] },
  { id: "rebelute", name: "Rebelute Digital Solutions", role: "Full Stack Developer", period: "January 2017 — December 2017", location: "Pune, India", relationship: "employment", public: true, projectIds: ["tweebr"] },
  { id: "proaxive", name: "Proaxive", role: "Founder", period: "Historical record", relationship: "founder", public: false, projectIds: [] },
  { id: "cygnet", name: "Cygnet Infotech Pvt. Ltd.", role: "Software Engineer", period: "June 2015 — December 2016", location: "Pune, India", relationship: "employment", public: true, projectIds: ["fastraxpos"] },
  { id: "signet", name: "Signet Technologies Pvt. Ltd.", role: "Technical Support Engineer / Intern", period: "2009 — 2013", relationship: "employment", public: false, projectIds: [] },
] as const;

export const careerProjects: readonly CareerProject[] = [
  { id: "rentora", name: "Rentora", shortLabel: "AI-first Operations OS", companyId: "independent", period: "2026 — Present", domain: "Operations", summary: "Natural-language requirements become structured material, inventory, sourcing, crew, logistics and readiness plans.", technologies: ["GenAI", "Planning engines", "Structured validation"], engineeringAreas: ["Deterministic language engine", "LLM fallback", "Preservation-first interpretation", "Semantic and verified validation", "Inventory planning", "Crew, logistics and readiness", "Evaluation and regression", "SIT and model comparison", "Human decision boundaries"], confidence: "VERIFIED", public: true, href: "/work/rentora" },
  { id: "edvora", name: "Edvora", shortLabel: "School OS", companyId: "independent", period: "2026 — Present", domain: "Education operations", summary: "A multi-tenant school platform spanning admissions, academics, identity, operational workflows and deployment.", technologies: ["Next.js", "Multi-tenant SaaS", "Workflow systems"], engineeringAreas: ["Product architecture", "Authentication", "Deployment"], confidence: "VERIFIED", public: true, href: "/work/edvora" },
  { id: "loom", name: "Loom", shortLabel: "Deployment Platform", companyId: "independent", period: "2026 — Present", domain: "Production engineering", summary: "Immutable releases, runtime health, rollback, environment governance and app-specific runtime configuration.", technologies: ["Node.js", "PM2", "Nginx"], engineeringAreas: ["Release activation", "Health verification", "Retention", "Runtime governance"], confidence: "VERIFIED", public: true, href: "/work/loom" },
  { id: "streamora", name: "Streamora", shortLabel: "Private Media Platform", companyId: "independent", period: "2026 — Present", domain: "Media infrastructure", summary: "Private uploads, storage, processing workers, metadata and signed access designed as one production system.", technologies: ["Next.js", "Private storage", "Workers"], engineeringAreas: ["Media processing", "Metadata", "Secure access", "Deployment"], confidence: "VERIFIED", public: true, href: "/work/streamora" },
  { id: "mastercard-vocalink", name: "Mastercard Vocalink", shortLabel: "Event processing / Fraud workflows", companyId: "barclays", period: "2021 — 2026", domain: "Financial crime systems", summary: "Kafka-based feedback delivery with bounded API retries and a dedicated retry/recovery topic.", technologies: ["Java", "Spring Boot", "Apache Kafka", "Resilience4j"], engineeringAreas: ["Event processing", "Bounded API retries", "Exponential backoff", "Retry and recovery topics"], confidence: "USER_RECALLED", public: true, detail: { problem: "Feedback events required dependable delivery to the Mastercard Vocalink Feedback API when the downstream service was unavailable.", architecture: "Events flowed through Apache Kafka to an Account Verification consumer, with Resilience4j handling bounded immediate API retries before failed events entered a dedicated Kafka retry/recovery topic.", engineering: "Worked with Kafka-based event processing and resilient Vocalink feedback delivery using bounded API retries, exponential backoff and a dedicated retry/recovery topic.", lessons: "Immediate API retries and scheduled deferred recovery are separate mechanisms and should not be described as one retry counter.", interviewTopics: ["Kafka delivery semantics", "Idempotency", "Immediate versus deferred retries", "Retry-topic recovery", "Failure recovery"], future: "Detailed historical and retrospective material is stored separately so proposed redesigns are never represented as Barclays implementation." } },
  { id: "barclays-identification-verification", name: "Barclays Identification & Verification (BIDV)", aliases: ["BIDV", "I&V", "Barclays I&V", "Identification & Verification", "Barclays Identification and Verification", "barclays-iv"], shortLabel: "Identity / Multi-channel login", companyId: "barclays", period: "2021 — 2026", domain: "Secure banking identity systems", summary: "Identity, authentication and verification journeys serving multiple Barclays channels through enterprise API and application boundaries.", technologies: ["Java", "Spring Boot", "Enterprise APIs"], engineeringAreas: ["Identity", "Authentication", "Verification", "Multi-channel login journeys", "Secure banking systems", "Backend integration", "Full-stack integration"], confidence: "VERIFIED", public: true, detail: { problem: "Identity, authentication and verification journeys must remain coherent across multiple secure banking channels.", architecture: "Enterprise identity and verification capabilities exposed through controlled service and API boundaries.", engineering: "Backend and full-stack integration across authentication, login and verification journeys.", lessons: "Identity workflows require explicit trust boundaries, predictable responses and careful failure handling.", interviewTopics: ["Authentication journeys", "Enterprise API boundaries", "Multi-channel consistency", "Trust boundaries"], future: "Protocol-level and channel-specific detail remains withheld until it can be verified." } },
  { id: "amazon-connect-voice", name: "Amazon Connect — Voice Systems", shortLabel: "Voice / Recognition", companyId: "barclays", period: "2021 — 2026", domain: "Customer interaction", summary: "Voice-interaction work involving recognition and suspicious-interaction detection within an Amazon Connect-related system.", technologies: ["Amazon Connect", "Voice systems"], engineeringAreas: ["Recognition flows", "Suspicious-interaction detection"], confidence: "PENDING_DETAIL", public: true, detail: { problem: "Voice interactions require dependable recognition and handling when an interaction appears suspicious.", architecture: "An Amazon Connect-related voice system; the exact AWS service terminology is intentionally not asserted.", engineering: "Contributed to voice recognition and suspicious-interaction detection workflows.", lessons: "Transient voice interfaces need observable transitions and explicit fallback behaviour.", interviewTopics: ["Voice workflows", "Recognition boundaries", "Fallback design"], future: "Exact AWS service terminology is pending documentation." } },
  { id: "master-table-management", name: "Master Table Management", shortLabel: "Banking product", companyId: "sysnik", period: "2018 — 2021", domain: "Banking", summary: "Full-stack master-data management for banking operations.", technologies: ["Angular", "Spring Boot", "Microsoft SQL Server"], engineeringAreas: ["Full-stack engineering", "Data management"], confidence: "VERIFIED", public: true },
  { id: "syscore-cbs", name: "Syscore CBS", shortLabel: "Core Banking System", companyId: "sysnik", period: "2018 — 2021", domain: "Core banking", summary: "Strategic microservices development within a core banking system.", technologies: ["Microservices"], engineeringAreas: ["Banking-domain engineering"], confidence: "VERIFIED", public: true },
  { id: "reporting-framework", name: "Reporting Framework", shortLabel: "Banking reporting", companyId: "sysnik", period: "2018 — 2021", domain: "Reporting", summary: "Reporting workflows across backend services and product UI.", technologies: ["BIRT", "Spring Boot", "Angular"], engineeringAreas: ["Reporting systems", "Full-stack engineering"], confidence: "VERIFIED", public: true },
  { id: "ui-builder", name: "Drag-and-Drop UI Builder", shortLabel: "Product tooling", companyId: "sysnik", period: "2018 — 2021", domain: "Developer tools", summary: "A visual interface builder created through proof-of-concept and technology evaluation work.", technologies: ["Angular", "Vue", "JavaScript"], engineeringAreas: ["Proof of concepts", "Technology evaluation"], confidence: "VERIFIED", public: true },
  { id: "tweebr", name: "Tweebr", shortLabel: "Full-stack product", companyId: "rebelute", period: "2017", domain: "Product engineering", summary: "Technology selection, architecture and delivery across application services, messaging and cloud infrastructure.", technologies: ["Spring Boot", "Laravel", "Vue", "AWS EC2", "AWS SQS", "Nexmo", "Twilio", "Textlocal"], engineeringAreas: ["Technology selection", "Repository pattern", "Architecture decisions"], confidence: "VERIFIED", public: true },
  { id: "fastraxpos", name: "FastraxPOS Digital Signage", shortLabel: "Software engineering foundation", companyId: "cygnet", period: "2015 — 2016", domain: "Digital signage", summary: "Client product development spanning a control-center application and ConnectWise ticket/detail integration.", technologies: ["Laravel", "JavaScript", "ConnectWise API"], engineeringAreas: ["Control center", "API integration", "Offshore client development"], confidence: "VERIFIED", public: true },
] as const;

export const education = [{ qualification: "Bachelor of Engineering", discipline: "Computer Science Engineering", institution: "Priyadarshini Institute of Engineering and Technology", location: "Nagpur", period: "2009 — 2012", public: true }] as const;
export const capabilityEvidence = { "Apache Kafka": ["mastercard-vocalink"], "Resilience4j": ["mastercard-vocalink"], "Retry Mechanisms": ["mastercard-vocalink"], "Spring Boot": ["mastercard-vocalink", "barclays-identification-verification", "master-table-management", "reporting-framework", "tweebr"], "Full Stack Engineering": ["barclays-identification-verification", "master-table-management", "reporting-framework", "tweebr"] } as const;
export const getCompany = (id: string) => companies.find((company) => company.id === id);
export const getProjectsForCompany = (companyId: string) => careerProjects.filter((project) => project.companyId === companyId && project.public);
const normalizeProjectKey = (value: string) => value.trim().toLocaleLowerCase("en").replace(/\band\b/g, "&").replace(/[^a-z0-9&]+/g, "");
export const getCareerProject = (idOrAlias: string) => {
  const key = normalizeProjectKey(idOrAlias);
  return careerProjects.find((project) => project.id === idOrAlias || project.aliases?.some((alias) => normalizeProjectKey(alias) === key));
};
